proprietary-files.txt: remove CNEService app
* Role according to Qualcomm:
  https://www.qualcomm.com/news/onq/2013/07/02/qualcomms-cne-bringing-smarts-3g4g-wi-fi-seamless-interworking
* When a SIM card is inserted into the YTX703L, the library fails to
  call Looper.init() in the telephony stack (log below). Figuring out
  why is not in top 100 priorities right now, so we are simply removing
  the service.

FATAL EXCEPTION: MainEventThread
Process: .dataservices, PID: 2422
java.lang.NoSuchMethodError: No direct method <init>(ILandroid/os/Looper;)V in
  class Landroid/telephony/PhoneStateListener; or its super classes (declaration
  of '/system/framework/framework.jar!classes2.dex)
       at com.quicinc.cne.CNE$8.<init>(CNE.java:2477)
       at com.quicinc.cne.CNE.registerPhoneStateListener(CNE.java:2477)
       at com.quicinc.cne.CNE.-wrap5(Unknown Source:0)
       at com.quicinc.cne.CNE$6.handleMessage(CNE.java:1681)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)

Change-Id: Ia6c433b6dd31fdb4b5eba8087f73713d3ea6f4e7
Signed-off-by: Vladimir Oltean <olteanv@gmail.com>